config/routes.rb
Spn::Application.routes.draw do
  resources :cellphones

  resources :resources

  resources :prayers

  resources :categories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
   get '/logout' => 'devise/sessions#destroy'
  end
  
  root :to => "prayers#index"
  resources :user, :controller => "users"

  match 'members/' => 'users#index'

end

app/models/cellphone.rb
class Cellphone < ActiveRecord::Base
  belongs_to :user

  attr_accessible :number, :active, :token
end

app/controllers/cellphones_controller.rb
class CellphonesController < ApplicationController
  # GET /cellphones
  # GET /cellphones.xml
  def index
    @cellphones = Cellphone.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cellphones }
    end
  end

  # GET /cellphones/1
  # GET /cellphones/1.xml
  def show
    @cellphone = Cellphone.find(params[:id])
    if params[:code] == @cellphone.token
      @cellphone.active = "true"
      @cellphone.save
      redirect_to(prayers_path, :notice => 'Your cell phone has been varified')
    end
  end

  # GET /cellphones/new
  # GET /cellphones/new.xml
  def new
    @cellphone = Cellphone.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cellphone }
    end
  end

  # GET /cellphones/1/edit
  def edit
    @cellphone = Cellphone.find(params[:id])
  end

  # POST /cellphones
  # POST /cellphones.xml
  def create
    @cellphone = current_user.build_cellphone(:token => "12345", :active => "false", :number => params[:number])

      if @cellphone.save
        redirect_to(@cellphone, :notice => 'Please enter your varification code')
      else
        render :action => "new"
      end
	
  end

  # PUT /cellphones/1
  # PUT /cellphones/1.xml
  def update
    @cellphone = Cellphone.find(params[:id])

    respond_to do |format|
      if @cellphone.update_attributes(params[:cellphone])
        format.html { redirect_to(@cellphone, :notice => 'Cellphone was successfully updated.') }
        format.xml  { head :ok }
      else	
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cellphone.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    @cellphone = Cellphone.find(params[:id])
    @cellphone.destroy

    redirect_to(cellphones_url) 


  end
end

app/helpers/cellphones_helper.rb
module CellphonesHelper
end

app/views/cellphones/_form.html.erb
<%= form_for(@cellphone) do |f| %>
  <% if @cellphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cellphone.errors.count, "error") %> prohibited this cellphone from being saved:</h2>

      <ul>
      <% @cellphone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cellphones/edit.html.erb
<h1>Editing cellphone</h1>

<%= render 'form' %>

<%= link_to 'Show', @cellphone %> |
<%= link_to 'Back', cellphones_path %>

app/views/cellphones/index.html.erb
<h1>Listing cellphones</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Active</th>
    <th>Token</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cellphones.each do |cellphone| %>
  <tr>
    <td><%= cellphone.number %></td>
    <td><%= cellphone.active %></td>
    <td><%= cellphone.token %></td>
    <td><%= cellphone.user_id %></td>
    <td><%= link_to 'Show', cellphone %></td>
    <td><%= link_to 'Edit', edit_cellphone_path(cellphone) %></td>
    <td><%= link_to 'Destroy', cellphone, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cellphone', new_cellphone_path %>

app/views/cellphones/new.html.erb
<% @page_title = "Cellphone Number" %>
<% @page_tagline = "What cellphone will you use to send us prayer requests via sms?" %>

<%= form_for(@cellphone) do |f| %>
  
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', cellphones_path %>

app/views/cellphones/show.html.erb
<% @page_title = "Verify" %>
<% @page_tagline = "Enter the code we sent to your cell phone" %>

<% form_tag cellphone_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :code %>
    <%= submit_tag "Submit Verification Code", :name => nil %>
  </p>
<% end %>

<%= link_to 'Back', cellphones_path %>