config/routes.rb
Spn::Application.routes.draw do
  resources :cellphones

  resources :resources

  resources :prayers

  resources :categories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
   get '/logout' => 'devise/sessions#destroy'
  end
  
  root :to => "prayers#index"
  resources :user, :controller => "users"

  match 'members/' => 'users#index'

end

app/views/resources/_form.html.erb
<%= semantic_form_for(@resource) do |f| %>
  <% f.inputs do %>
	<%= f.input :title %><br />
	<%= f.input :description %><br />
	<%= f.input :url %><br />
	<%= f.input :category, :include_blank => false, :input_html => { :class => 'my-request' }  %>
   <% end %>
   <%= f.buttons  %>	
<% end %>

 

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<% @page_title = "Thank You For Sharing" %>
<% @page_tagline = "Below are some resources for dealing with #{@category.name}" %>

<p><strong><%= current_user.firstname %></strong>, People from around the world will see and pray for your request. Even now someone is likely already praying for you this very moment. We hope you find the following resources for <%= @category.name %>.</p>
<p>Best Regards,<br />
Aaron Mills</p>
<br />
<h2 style="border-bottom:1px solid;">Dealing With <%= @category.name %></h2>

<% if can? :update, Category%>
<p style="float:right;"><%= link_to 'Edit This Category Name', edit_category_path(@category), :class => 'button' %></p><br /><br />
<% end %>




<% @resources.each do |resource| %>
<h3><%= resource.title %></h3>
<p><%= resource.description %></p>
<p><a href="<%= resource.url %>">Visit Website</a></p><hr /><br />
<% end %>


<br />
<%= will_paginate @prayers %>
<br />

<% if can? :create, Resource %>
<p style="float:right;"><%= link_to 'Create a new resource', new_resource_path, :class => 'button' %></p>
<% end %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>

<p>
  <b>Url:</b>
  <%= @resource.url %>
</p>

<p>
  <b>Category:</b>
  <%= @resource.category_id %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>