config/routes.rb
Spn::Application.routes.draw do
  resources :cellphones

  resources :resources

  resources :prayers

  resources :categories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
   get '/logout' => 'devise/sessions#destroy'
  end
  
  root :to => "prayers#index"
  resources :user, :controller => "users"

  match 'members/' => 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :prayers
	has_many :resources
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
	layout "prayers"
  load_and_authorize_resource

  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
		@categories = Category.all
    @category = Category.find(params[:id])
    
		@prayers = Prayer.returncat(params[:id]).paginate :page => params[:page], :per_page => 10, :order => 'created_at DESC'

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end


  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])
    


    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% @page_title = "Categories" %>
<% @page_tagline = "Find prayer requests by category" %>
<br />
<% @categories.each do |category| %>
<h3><%= link_to category.name, category %> <% if can? :update, @category %> | <%= link_to 'Edit', edit_category_path(category) %> <% end %><% if can? :delete, @category %>| <%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :destroy %> <% end %></h3>
<% end %>



<% if can? :create, @category %>
<p>
<%= link_to 'New Category', new_category_path %>
</p>
<% end %>

app/views/categories/new.html.erb
<% @page_title = "Create a Category" %>
<% @page_tagline = "Enter the details for the new category below" %>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/resource.html.erb
<% @page_title = "Dealing with #{@category.name}" %>
<% @page_tagline = "Thank you" %>

<% if can? :update, Category%>
<%= link_to 'Edit This Category Name', edit_category_path(@category) %>
<% end %>

<% @resources.each do |resource| %>
<p><%= resource.title %></p><br />
<p><%= resource.url %></p>
<% end %>

app/views/categories/show.html.erb
<% @page_title = "#{@category.name} Requests" %>
<% @page_tagline = "Pray for people dealing with #{@category.name}" %>

<% if can? :update, Category%>
<h2><%= link_to 'Edit This Category Name', edit_category_path(@category) %></h2><hr /><br />
<% end %>

<% @prayers.each do |prayer| %>

    <div class="post">
          <div class="meta">
            <span class="category">Category: <a href="#"><%= prayer.category.name %></a></span>
            <span class="date">Posted <%= time_ago_in_words(prayer.created_at) %> ago, by <%= prayer.user.firstname %> <%= prayer.user.lastname %></span>
          </div>
	  <a href="#" class="img-load"><img src="<%= avatar_url(prayer.user) %>" class="lightview" width="80px" /></a>
          <%= prayer.request %>
    <% if user_signed_in? %><% if current_user.id == prayer.user.id %><p style="float:right;"><br />
    <%= link_to 'Edit This Request', edit_prayer_path(prayer), :class => 'button' %></p>
    
    <% end %><% end %> 

    </div>

<% end %>
<br style="clear:both;" /><%= will_paginate @prayers %>
  
<br  style="clear:both;" />